# Results
Di Tuccio Gianluca, Orsini Lorenzo

In [1]:
from tqdm import tqdm
from z3 import *
from numpy import random
import os
import pandas as pd
from utils.utils import *

## Models without Rotation

Let's have a look on some statistics about the four models:

In [16]:
results = pd.read_csv('utils/datasets/results.csv')
Statistics({'CP + SB w/out R':results['CP + SB w/out R'], 
            'SAT + SB w/out R':results['SAT + SB w/out R'],
            'SMT + SB w/out R':results['SMT + SB w/out R'],
            'MIP + SB w/out R':results['MIP + SB w/out R']},
            timeout=300)
results = results.replace('TIMEOUT', 0)
results = results.astype(float)
results = results.reset_index(drop=True)
results = results.set_index("Instance")
print()
print('GREEN --> BEST VALUE,\nYELLOW --> WORST VALUE,\nRED --> TIMEOUT')
results.style.apply(highlight_max, axis=1).apply(highlight_min, axis=1).apply(highlight_timeout, axis=1).set_properties(**{'border-top': '2px solid', 'border-bottom': '2px solid'}, axis=1)

TIMEOUT is seen as 300s.

+------------------+-----------------+------------------+------------------+------------------+
|                  | CP + SB w/out R | SAT + SB w/out R | SMT + SB w/out R | MIP + SB w/out R |
+------------------+-----------------+------------------+------------------+------------------+
|  Total Time [s]  |         491.659 |          993.825 |         2060.039 |         2504.815 |
|     Max [s]      |           300.0 |            300.0 |            300.0 |            300.0 |
|     Min [s]      |           0.161 |            0.043 |            0.035 |            0.002 |
|     Mean [s]     |          12.291 |           24.846 |           51.501 |            62.62 |
|     Std [s]      |          48.287 |           71.622 |           99.084 |          113.628 |
| Instances Solved |           39/40 |            38/40 |            35/40 |            33/40 |
+------------------+-----------------+------------------+------------------+------------------+

GREEN --> BEST VALUE,
YELLOW --> WORST VALUE,
RED --> TIMEOUT

Then, let's see the number of minimums and maximums for each models (for each instance we've computed the min and the max, we count them and we've divided them by the first 20 instances and the last 20 instances):

In [8]:
Results(results, ['CP + SB w/out R','SAT + SB w/out R','SMT + SB w/out R','MIP + SB w/out R'])

+------------------------+-----------------+------------------+------------------+------------------+
|                        | CP + SB w/out R | SAT + SB w/out R | SMT + SB w/out R | MIP + SB w/out R |
+------------------------+-----------------+------------------+------------------+------------------+
| Maximums (First Half)  |            5/20 |             7/20 |             6/20 |             2/20 |
| Minimums (First Half)  |            4/20 |             0/20 |             0/20 |            16/20 |
|  Timeout (First Half)  |            0/20 |             0/20 |             0/20 |             0/20 |
|                        |                 |                  |                  |                  |
| Maximums (Second Half) |            2/20 |             2/20 |            12/20 |             4/20 |
| Minimums (Second Half) |           10/20 |             1/20 |             3/20 |             6/20 |
| Timeout (Second Half)  |            1/20 |             2/20 |             5/20 |             7/20 |
|                        |                 |                  |                  |                  |
|     Total Minimums     |           14/40 |             1/40 |             3/40 |            22/40 |
|     Total Maximums     |            7/40 |             9/40 |            18/40 |             6/40 |
|     Total Timeout      |            1/40 |             2/40 |             5/40 |             7/40 |
+------------------------+-----------------+------------------+------------------+------------------+

## Models with Rotation

In [17]:
results = pd.read_csv('utils/datasets/results_rotation.csv')
Statistics({'CP + SB + R':results['CP + SB + R'], 
            'SAT + SB + R':results['SAT + SB + R'],
            'SMT + SB + R':results['SMT + SB + R'],
            'MIP + SB + R':results['MIP + SB + R']},
            timeout=300)
results = results.replace('TIMEOUT', 0)
results = results.astype(float)
results = results.reset_index(drop=True)
results = results.set_index("Instance")
print()
print('GREEN --> BEST VALUE,\nYELLOW --> WORST VALUE,\nRED --> TIMEOUT')
results.style.apply(highlight_max, axis=1).apply(highlight_min, axis=1).apply(highlight_timeout, axis=1).set_properties(**{'border-top': '2px solid', 'border-bottom': '2px solid'}, axis=1)

TIMEOUT is seen as 300s.

+------------------+-------------+--------------+--------------+--------------+
|                  | CP + SB + R | SAT + SB + R | SMT + SB + R | MIP + SB + R |
+------------------+-------------+--------------+--------------+--------------+
|  Total Time [s]  |    1984.004 |     2433.407 |     3870.686 |     4838.492 |
|     Max [s]      |       300.0 |        300.0 |        300.0 |        300.0 |
|     Min [s]      |       0.162 |        0.134 |        0.047 |        0.002 |
|     Mean [s]     |        49.6 |       60.835 |       96.767 |      120.962 |
|     Std [s]      |      97.914 |      101.056 |      134.332 |      136.516 |
| Instances Solved |       36/40 |        36/40 |        29/40 |        27/40 |
+------------------+-------------+--------------+--------------+--------------+

GREEN --> BEST VALUE,
YELLOW --> WORST VALUE,
RED --> TIMEOUT

In [14]:
Results(results, ['CP + SB + R','SAT + SB + R','SMT + SB + R','MIP + SB + R'])

+------------------------+-------------+--------------+--------------+--------------+
|                        | CP + SB + R | SAT + SB + R | SMT + SB + R | MIP + SB + R |
+------------------------+-------------+--------------+--------------+--------------+
| Maximums (First Half)  |        1/20 |        16/20 |         1/20 |         2/20 |
| Minimums (First Half)  |        2/20 |         0/20 |         3/20 |        15/20 |
|  Timeout (First Half)  |        0/20 |         0/20 |         1/20 |         3/20 |
|                        |             |              |              |              |
| Maximums (Second Half) |        6/20 |         4/20 |         4/20 |         6/20 |
| Minimums (Second Half) |        9/20 |         1/20 |         5/20 |         5/20 |
| Timeout (Second Half)  |        4/20 |         4/20 |        10/20 |        10/20 |
|                        |             |              |              |              |
|     Total Minimums     |       11/40 |         1/40 |         8/40 |        20/40 |
|     Total Maximums     |        7/40 |        20/40 |         5/40 |         8/40 |
|     Total Timeout      |        4/40 |         4/40 |        11/40 |        13/40 |
+------------------------+-------------+--------------+--------------+--------------+