# Results
Di Tuccio Gianluca, Orsini Lorenzo

In [1]:
from tqdm import tqdm
from z3 import *
from numpy import random
import os
import pandas as pd



'''
SET HERE THE PATH OF THE MAIN FOLDER (i.e VLSI folder)
            |
            |
            V
'''

os.chdir('/Users/gianlucadituccio/Documents/VLSI')
from utils.utils import *

## Models without Rotation

Let's have a look on some statistics about the four models:

In [2]:
results = pd.read_csv('utils/datasets/results.csv')
Statistics({'CP':results['time_CP'], 
            'SAT':results['time_SAT'],
            'SMT':results['time_SMT'],
            'MIP':results['time_MIP']}, 
           {'h_min':results['h_min'], 
            'CP':results['h_CP'], 
            'SAT':results['h_SAT'],
            'SMT':results['h_SMT'],
            'MIP':results['h_MIP']},
            timeout=300)

TIMEOUT is seen as 300s.

+------------------+---------+----------+----------+----------+
|                  |      CP |      SAT |      SMT |      MIP |
+------------------+---------+----------+----------+----------+
|  Total Time [s]  | 576.446 | 1684.761 | 2472.513 | 2815.366 |
|     Max [s]      |   300.0 |    300.0 |    300.0 |    300.0 |
|     Min [s]      |   0.163 |    0.061 |    0.026 |    0.007 |
|     Mean [s]     |  14.411 |   42.119 |   61.813 |   70.384 |
|     Std [s]      |  50.056 |   93.701 |   96.325 |  110.566 |
| Instances Solved |   39/40 |    36/40 |    36/40 |    34/40 |
|    Optimal H     |   39/40 |    36/40 |    36/40 |    34/40 |
+------------------+---------+----------+----------+----------+

Then, let's see the number of minimums and maximums for each models (for each instance we've computed the min and the max, we count them and we've divided them by the first 20 instances and the last 20 instances):

In [3]:
res = results.drop(columns=['h_CP','h_SAT','h_SMT','h_MIP','h_min'])
res = res.rename(columns={'time_CP':'CP', 'time_SMT':'SMT', 'time_SAT':'SAT', 'time_MIP':'MIP'})
res = res.replace('TIMEOUT', 0)
res = res.astype(float)
res = res.reset_index(drop=True)
res = res.set_index("Instance")
Results(res, ['CP','SAT','SMT','MIP'])

+------------------------+-------+-------+-------+-------+
|                        |    CP |   SAT |   SMT |   MIP |
+------------------------+-------+-------+-------+-------+
| Maximums (First Half)  |  3/20 |  9/20 |  5/20 |  3/20 |
| Minimums (First Half)  | 11/20 |  0/20 |  0/20 |  9/20 |
|  Timeout (First Half)  |  0/20 |  0/20 |  0/20 |  0/20 |
|                        |       |       |       |       |
| Maximums (Second Half) |  2/20 |  1/20 | 10/20 |  7/20 |
| Minimums (Second Half) | 12/20 |  0/20 |  0/20 |  8/20 |
| Timeout (Second Half)  |  1/20 |  4/20 |  4/20 |  6/20 |
|                        |       |       |       |       |
|     Total Minimums     | 23/40 |  0/40 |  0/40 | 17/40 |
|     Total Maximums     |  5/40 | 10/40 | 15/40 | 10/40 |
|     Total Timeout      |  1/40 |  4/40 |  4/40 |  6/40 |
+------------------------+-------+-------+-------+-------+

In [4]:
res = res[['CP','SAT','SMT','MIP']]
res.style.apply(highlight_max, axis=1).apply(highlight_min, axis=1).set_properties(**{'border-top': '2px solid', 'border-bottom': '2px solid'}, axis=1)

## Models with Rotation

In [5]:
results = pd.read_csv('utils/datasets/results_rotation.csv')
Statistics({'CP':results['time_CP'], 
            'SAT':results['time_SAT'],
            'SMT':results['time_SMT'],
            'MIP':results['time_MIP']}, 
           {'h_min':results['h_min'], 
            'CP':results['h_CP'], 
            'SAT':results['h_SAT'],
            'SMT':results['h_SMT'],
            'MIP':results['h_MIP']},
            timeout=300)

TIMEOUT is seen as 300s.

+------------------+----------+----------+----------+----------+
|                  |       CP |      SAT |      SMT |      MIP |
+------------------+----------+----------+----------+----------+
|  Total Time [s]  | 3725.503 | 3444.205 | 6000.952 | 4109.279 |
|     Max [s]      |    300.0 |    300.0 |    300.0 |    300.0 |
|     Min [s]      |    0.163 |    0.074 |    0.042 |    0.001 |
|     Mean [s]     |   93.138 |   86.105 |  150.024 |  102.732 |
|     Std [s]      |  131.409 |  115.012 |  129.653 |  134.659 |
| Instances Solved |    29/40 |    33/40 |    28/40 |    28/40 |
|    Optimal H     |    29/40 |    33/40 |    28/40 |    28/40 |
+------------------+----------+----------+----------+----------+

In [6]:
res = results.drop(columns=['h_CP','h_SAT','h_SMT','h_MIP','h_min'])
res = res.rename(columns={'time_CP':'CP', 'time_SMT':'SMT', 'time_SAT':'SAT', 'time_MIP':'MIP'})
res = res.replace('TIMEOUT', 0)
res = res.astype(float)
res = res.reset_index(drop=True)
res = res.set_index("Instance")
Results(res, ['CP','SAT','SMT','MIP'])

+------------------------+-------+-------+-------+-------+
|                        |    CP |   SAT |   SMT |   MIP |
+------------------------+-------+-------+-------+-------+
| Maximums (First Half)  |  2/20 |  6/20 | 12/20 |  0/20 |
| Minimums (First Half)  |  6/20 |  1/20 |  0/20 | 13/20 |
|  Timeout (First Half)  |  1/20 |  0/20 |  0/20 |  1/20 |
|                        |       |       |       |       |
| Maximums (Second Half) |  6/20 |  6/20 |  7/20 |  1/20 |
| Minimums (Second Half) | 12/20 |  2/20 |  4/20 |  2/20 |
| Timeout (Second Half)  | 10/20 |  7/20 | 12/20 | 11/20 |
|                        |       |       |       |       |
|     Total Minimums     | 18/40 |  3/40 |  4/40 | 15/40 |
|     Total Maximums     |  8/40 | 12/40 | 19/40 |  1/40 |
|     Total Timeout      | 11/40 |  7/40 | 12/40 | 12/40 |
+------------------------+-------+-------+-------+-------+

In [7]:
res.style.apply(highlight_max, axis=1).apply(highlight_min, axis=1).set_properties(**{'border-top': '2px solid', 'border-bottom': '2px solid'}, axis=1)